#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# general space settings
yabai -m config external_bar               all:49:0     \
                window_border              on           \
                window_zoom_persist        off          \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_border_width        5            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_animation_duration  0.22         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                mouse_follows_focus         off         \
                focus_follows_mouse         off         \
                window_origin_display       default     \
                window_placement            second_child\
                split_ratio                 0.50        \
                auto_balance                off         \
                mouse_modifier              ctrl        \
                                                        \
                layout                      bsp         \
                top_padding                 14          \
                bottom_padding              14          \
                left_padding                14          \
                right_padding               14          \
                window_gap                  8

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Settings" app="^Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="System Information" app="System Information" title="System Information" manage=off
yabai -m rule --add label="Outlook" app="^Outlook$" title="Outlook" manage=off
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams$" title="Microsoft Teams" manage=off

borders active_color=0xffCAD3F5 inactive_color=0xbb282E44 hidpi=on width=5.0 2>/dev/null 1>&2 &

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 nvim
setup_space 2 web
setup_space 3 media

# move some apps automatically to specific spaces
yabai -m rule --add app="^Kitty$" space=^1
yabai -m rule --add app="^Firefox$" space=^2
yabai -m rule --add app="^Spotify$" space=3
yabai -m rule --add app="^Obsidian$" space=3

echo "yabai configuration loaded.."
