color = ''
project-name = 'default'
[default]
account_id = 'acct_1P94y7022YhxyumL'
device_name = 'Chongs-Laptop.local'
display_name = 'OyenCov'
live_mode_api_key = 'rk_live_***********************************************************************************************J2og'
live_mode_key_expires_at = '2024-08-04'
live_mode_pub_key = 'pk_live_51P94y7022YhxyumL6x1qYDcVoUy3lHuRGWrwuQqN1pgMY1YbK8weWisPF9SuqagPOhLyW8KaC9mgQrLjcp0ScXYw00FYfqatb6'
test_mode_api_key = 'rk_test_51P94y7022YhxyumLrScqcUz1dL4weimsGO1iFfzt6CyZWqES6KIgA8q2qOieGBPIzfYoCR0tQfGGbxJUm7iGG4dZ00UQ7ZCoWB'
test_mode_key_expires_at = '2024-08-04'
test_mode_pub_key = 'pk_test_51P94y7022YhxyumLk1lQkDl1Faf7jy2ZvBUdf2SE5gMBXMN3jKbBKEh9wmEz2rv4xMbzKTo5RjYwQmTSV29I7lOj00mN9jbs0S'

